CREATE OR REPLACE VIEW TOUR_ACTIVITIES AS SELECT AC.ID AC_ID, AC.BODY AC_BODY, T.ID TOUR_ID 
FROM ACTIVITY AC 
INNER JOIN FEATURE F ON F.ACTIVITY_FK = AC.ID 
INNER JOIN TOUR T ON F.TOUR_FK = T.ID;

DROP PROCEDURE IF EXISTS PUT_USER;
DELIMITER //
CREATE PROCEDURE PUT_USER
(IN P_ID INT, IN P_NAME VARCHAR(45), IN P_EMAIL VARCHAR(45), IN P_BIRTH_DATE DATE, 
IN P_PASSWORD VARCHAR(45), IN P_COUNTRY_ID VARCHAR(45))
BEGIN
DECLARE V_COUNTRY_ID INT;
    SELECT ID INTO V_COUNTRY_ID FROM COUNTRY WHERE NAME = P_COUNTRY_ID;
	INSERT INTO USER (ID,NAME, EMAIL, BIRTH_DATE, PASSWORD, COUNTRY_FK) 
				VALUES (P_ID, P_NAME, P_EMAIL, P_BIRTH_DATE, P_PASSWORD, V_COUNTRY_ID);
END 
//DELIMITER ;

DROP PROCEDURE IF EXISTS ADD_TO_FAV;
DELIMITER //
CREATE PROCEDURE ADD_TO_FAV
(IN P_USER_ID INT, IN P_TOUR_ID INT)
BEGIN
	INSERT INTO FAVORITE (USER_ID, TOUR_ID) VALUES (P_USER_ID, P_TOUR_ID);
END 
//DELIMITER ;

DROP PROCEDURE IF EXISTS REMOVE_FROM_FAV;
DELIMITER //
CREATE PROCEDURE REMOVE_FROM_FAV
(IN P_USER_ID INT, IN P_TOUR_ID INT)
BEGIN
	DELETE FROM tourdb.FAVORITE WHERE USER_ID = P_USER_ID AND TOUR_ID = P_TOUR_ID;
END 
//DELIMITER ;

DROP PROCEDURE IF EXISTS PUT_TOUR;
DELIMITER //
CREATE PROCEDURE PUT_TOUR
(IN P_NAME VARCHAR(45), IN P_DESC VARCHAR(100), IN P_RATING FLOAT, IN P_LEAVE_DATE DATE, P_RETURN_DATE DATE,
IN P_PRICE DOUBLE, IN P_SEATS INT, IN P_CAT INT, IN P_COUN INT)
BEGIN
DECLARE V_COUNTRY_ID INT;
    SELECT ID INTO V_COUNTRY_ID FROM COUNTRY WHERE NAME = P_COUN;
	INSERT INTO TOUR (NAME, DESCRIPTION, RATING, LEAVE_DATE, RETURN_DATE, PRICE, SEATS, CATEGORY_FK,COUNTRY_FK) 
	VALUES(P_NAME, P_DESC, P_RATING, P_LEAVE_DATE, P_RETURN_DATE, P_PRICE, P_SEATS, P_CAT, V_COUNTRY_ID);
END 
//DELIMITER ;

DROP PROCEDURE IF EXISTS LINK_ACTIVITY;
DELIMITER //
CREATE PROCEDURE LINK_ACTIVITY
(IN P_ID_TOUR INT, IN P_ID_ACT INT)
BEGIN
	INSERT INTO FEATURE (TOUR_FK, ACTIVITY_FK) VALUES (P_ID_TOUR,P_ID_ACT);
END 
//DELIMITER ;
   INSERT INTO COUNTRY (NAME) VALUES ('Afganistan');
   INSERT INTO COUNTRY (NAME) VALUES ('Albania');
   INSERT INTO COUNTRY (NAME) VALUES ('Algeria');
   INSERT INTO COUNTRY (NAME) VALUES ('American ');
   INSERT INTO COUNTRY (NAME) VALUES ('Andorra');
   INSERT INTO COUNTRY (NAME) VALUES ('Angola');
   INSERT INTO COUNTRY (NAME) VALUES ('Anguilla');
   INSERT INTO COUNTRY (NAME) VALUES ('Antigua & Barbuda');
   INSERT INTO COUNTRY (NAME) VALUES ('Argentina');
   INSERT INTO COUNTRY (NAME) VALUES ('Armenia');
   INSERT INTO COUNTRY (NAME) VALUES ('Aruba');
   INSERT INTO COUNTRY (NAME) VALUES ('Australia');
   INSERT INTO COUNTRY (NAME) VALUES ('Austria');
   INSERT INTO COUNTRY (NAME) VALUES ('Azerbaijan');
   INSERT INTO COUNTRY (NAME) VALUES ('Bahamas');
   INSERT INTO COUNTRY (NAME) VALUES ('Bahrain');
   INSERT INTO COUNTRY (NAME) VALUES ('Bangladesh');
   INSERT INTO COUNTRY (NAME) VALUES ('Barbados');
   INSERT INTO COUNTRY (NAME) VALUES ('Belarus');
   INSERT INTO COUNTRY (NAME) VALUES ('Belgium');
   INSERT INTO COUNTRY (NAME) VALUES ('Belize');
   INSERT INTO COUNTRY (NAME) VALUES ('Benin');
   INSERT INTO COUNTRY (NAME) VALUES ('Bermuda');
   INSERT INTO COUNTRY (NAME) VALUES ('Bhutan');
   INSERT INTO COUNTRY (NAME) VALUES ('Bolivia');
   INSERT INTO COUNTRY (NAME) VALUES ('Bonaire');
   INSERT INTO COUNTRY (NAME) VALUES ('Bosnia & Herzegovina');
   INSERT INTO COUNTRY (NAME) VALUES ('Botswana');
   INSERT INTO COUNTRY (NAME) VALUES ('Brazil');
   INSERT INTO COUNTRY (NAME) VALUES ('British Indian Ocean Ter');
   INSERT INTO COUNTRY (NAME) VALUES ('Brunei');
   INSERT INTO COUNTRY (NAME) VALUES ('Bulgaria');
   INSERT INTO COUNTRY (NAME) VALUES ('Burkina Faso');
   INSERT INTO COUNTRY (NAME) VALUES ('Burundi');
   INSERT INTO COUNTRY (NAME) VALUES ('Cambodia');
   INSERT INTO COUNTRY (NAME) VALUES ('Cameroon');
   INSERT INTO COUNTRY (NAME) VALUES ('Canada');
   INSERT INTO COUNTRY (NAME) VALUES ('Canary Islands');
   INSERT INTO COUNTRY (NAME) VALUES ('Cape Verde');
   INSERT INTO COUNTRY (NAME) VALUES ('Cayman Islands');
   INSERT INTO COUNTRY (NAME) VALUES ('Central African Republic');
   INSERT INTO COUNTRY (NAME) VALUES ('Chad');
   INSERT INTO COUNTRY (NAME) VALUES ('Channel Islands');
   INSERT INTO COUNTRY (NAME) VALUES ('Chile');
   INSERT INTO COUNTRY (NAME) VALUES ('China');
   INSERT INTO COUNTRY (NAME) VALUES ('Christmas Island');
   INSERT INTO COUNTRY (NAME) VALUES ('Cocos Island');
   INSERT INTO COUNTRY (NAME) VALUES ('Colombia');
   INSERT INTO COUNTRY (NAME) VALUES ('Comoros');
   INSERT INTO COUNTRY (NAME) VALUES ('Congo');
   INSERT INTO COUNTRY (NAME) VALUES ('Cook Islands');
   INSERT INTO COUNTRY (NAME) VALUES ('Costa Rica');
   INSERT INTO COUNTRY (NAME) VALUES ('Cote DIvoire');
   INSERT INTO COUNTRY (NAME) VALUES ('Croatia');
   INSERT INTO COUNTRY (NAME) VALUES ('Cuba');
   INSERT INTO COUNTRY (NAME) VALUES ('Curaco');
   INSERT INTO COUNTRY (NAME) VALUES ('Cyprus');
   INSERT INTO COUNTRY (NAME) VALUES ('Czech Republic');
   INSERT INTO COUNTRY (NAME) VALUES ('Denmark');
   INSERT INTO COUNTRY (NAME) VALUES ('Djibouti');
   INSERT INTO COUNTRY (NAME) VALUES ('Dominica');
   INSERT INTO COUNTRY (NAME) VALUES ('Dominican Republic');
   INSERT INTO COUNTRY (NAME) VALUES ('East Timor');
   INSERT INTO COUNTRY (NAME) VALUES ('Ecuador');
   INSERT INTO COUNTRY (NAME) VALUES ('Egypt');
   INSERT INTO COUNTRY (NAME) VALUES ('El Salvador');
   INSERT INTO COUNTRY (NAME) VALUES ('Equatorial Guinea');
   INSERT INTO COUNTRY (NAME) VALUES ('Eritrea');
   INSERT INTO COUNTRY (NAME) VALUES ('Estonia');
   INSERT INTO COUNTRY (NAME) VALUES ('Ethiopia');
   INSERT INTO COUNTRY (NAME) VALUES ('Falkland Islands');
   INSERT INTO COUNTRY (NAME) VALUES ('Faroe Islands');
   INSERT INTO COUNTRY (NAME) VALUES ('Fiji');
   INSERT INTO COUNTRY (NAME) VALUES ('Finland');
   INSERT INTO COUNTRY (NAME) VALUES ('France');
   INSERT INTO COUNTRY (NAME) VALUES ('French Guiana');
   INSERT INTO COUNTRY (NAME) VALUES ('French Polynesia');
   INSERT INTO COUNTRY (NAME) VALUES ('French Southern Ter');
   INSERT INTO COUNTRY (NAME) VALUES ('Gabon');
   INSERT INTO COUNTRY (NAME) VALUES ('Gambia');
   INSERT INTO COUNTRY (NAME) VALUES ('Georgia');
   INSERT INTO COUNTRY (NAME) VALUES ('Germany');
   INSERT INTO COUNTRY (NAME) VALUES ('Ghana');
   INSERT INTO COUNTRY (NAME) VALUES ('Gibraltar');
   INSERT INTO COUNTRY (NAME) VALUES ('Great Britain');
   INSERT INTO COUNTRY (NAME) VALUES ('Greece');
   INSERT INTO COUNTRY (NAME) VALUES ('Greenland');
   INSERT INTO COUNTRY (NAME) VALUES ('Grenada');
   INSERT INTO COUNTRY (NAME) VALUES ('Guadeloupe');
   INSERT INTO COUNTRY (NAME) VALUES ('Guam');
   INSERT INTO COUNTRY (NAME) VALUES ('Guatemala');
   INSERT INTO COUNTRY (NAME) VALUES ('Guinea');
   INSERT INTO COUNTRY (NAME) VALUES ('Guyana');
   INSERT INTO COUNTRY (NAME) VALUES ('Haiti');
   INSERT INTO COUNTRY (NAME) VALUES ('Hawaii');
   INSERT INTO COUNTRY (NAME) VALUES ('Honduras');
   INSERT INTO COUNTRY (NAME) VALUES ('Hong Kong');
   INSERT INTO COUNTRY (NAME) VALUES ('Hungary');
   INSERT INTO COUNTRY (NAME) VALUES ('Iceland');
   INSERT INTO COUNTRY (NAME) VALUES ('Indonesia');
   INSERT INTO COUNTRY (NAME) VALUES ('India');
   INSERT INTO COUNTRY (NAME) VALUES ('Iran');
   INSERT INTO COUNTRY (NAME) VALUES ('Iraq');
   INSERT INTO COUNTRY (NAME) VALUES ('Ireland');
   INSERT INTO COUNTRY (NAME) VALUES ('Isle of Man');
   INSERT INTO COUNTRY (NAME) VALUES ('Israel');
   INSERT INTO COUNTRY (NAME) VALUES ('Italy');
   INSERT INTO COUNTRY (NAME) VALUES ('Jamaica');
   INSERT INTO COUNTRY (NAME) VALUES ('Japan');
   INSERT INTO COUNTRY (NAME) VALUES ('Jordan');
   INSERT INTO COUNTRY (NAME) VALUES ('Kazakhstan');
   INSERT INTO COUNTRY (NAME) VALUES ('Kenya');
   INSERT INTO COUNTRY (NAME) VALUES ('Kiribati');
   INSERT INTO COUNTRY (NAME) VALUES ('Korea North');
   INSERT INTO COUNTRY (NAME) VALUES ('Korea Sout');
   INSERT INTO COUNTRY (NAME) VALUES ('Kuwait');
   INSERT INTO COUNTRY (NAME) VALUES ('Kyrgyzstan');
   INSERT INTO COUNTRY (NAME) VALUES ('Laos');
   INSERT INTO COUNTRY (NAME) VALUES ('Latvia');
   INSERT INTO COUNTRY (NAME) VALUES ('Lebanon');
   INSERT INTO COUNTRY (NAME) VALUES ('Lesotho');
   INSERT INTO COUNTRY (NAME) VALUES ('Liberia');
   INSERT INTO COUNTRY (NAME) VALUES ('Libya');
   INSERT INTO COUNTRY (NAME) VALUES ('Liechtenstein');
   INSERT INTO COUNTRY (NAME) VALUES ('Lithuania');
   INSERT INTO COUNTRY (NAME) VALUES ('Luxembourg');
   INSERT INTO COUNTRY (NAME) VALUES ('Macau');
   INSERT INTO COUNTRY (NAME) VALUES ('Macedonia');
   INSERT INTO COUNTRY (NAME) VALUES ('Madagascar');
   INSERT INTO COUNTRY (NAME) VALUES ('Malaysia');
   INSERT INTO COUNTRY (NAME) VALUES ('Malawi');
   INSERT INTO COUNTRY (NAME) VALUES ('Maldives');
   INSERT INTO COUNTRY (NAME) VALUES ('Mali');
   INSERT INTO COUNTRY (NAME) VALUES ('Malta');
   INSERT INTO COUNTRY (NAME) VALUES ('Marshall Islands');
   INSERT INTO COUNTRY (NAME) VALUES ('Martinique');
   INSERT INTO COUNTRY (NAME) VALUES ('Mauritania');
   INSERT INTO COUNTRY (NAME) VALUES ('Mauritius');
   INSERT INTO COUNTRY (NAME) VALUES ('Mayotte');
   INSERT INTO COUNTRY (NAME) VALUES ('Mexico');
   INSERT INTO COUNTRY (NAME) VALUES ('Midway Islands');
   INSERT INTO COUNTRY (NAME) VALUES ('Moldova');
   INSERT INTO COUNTRY (NAME) VALUES ('Monaco');
   INSERT INTO COUNTRY (NAME) VALUES ('Mongolia');
   INSERT INTO COUNTRY (NAME) VALUES ('Montserrat');
   INSERT INTO COUNTRY (NAME) VALUES ('Morocco');
   INSERT INTO COUNTRY (NAME) VALUES ('Mozambique');
   INSERT INTO COUNTRY (NAME) VALUES ('Myanmar');
   INSERT INTO COUNTRY (NAME) VALUES ('Nambia');
   INSERT INTO COUNTRY (NAME) VALUES ('Nauru');
   INSERT INTO COUNTRY (NAME) VALUES ('Nepal');
   INSERT INTO COUNTRY (NAME) VALUES ('Netherland Antilles');
   INSERT INTO COUNTRY (NAME) VALUES ('Netherlands');
   INSERT INTO COUNTRY (NAME) VALUES ('Nevis');
   INSERT INTO COUNTRY (NAME) VALUES ('New Caledonia');
   INSERT INTO COUNTRY (NAME) VALUES ('New Zealand');
   INSERT INTO COUNTRY (NAME) VALUES ('Nicaragua');
   INSERT INTO COUNTRY (NAME) VALUES ('Niger');
   INSERT INTO COUNTRY (NAME) VALUES ('Nigeria');
   INSERT INTO COUNTRY (NAME) VALUES ('Niue');
   INSERT INTO COUNTRY (NAME) VALUES ('Norfolk Island');
   INSERT INTO COUNTRY (NAME) VALUES ('Norway');
   INSERT INTO COUNTRY (NAME) VALUES ('Oman');
   INSERT INTO COUNTRY (NAME) VALUES ('Pakistan');
   INSERT INTO COUNTRY (NAME) VALUES ('Palau Island');
   INSERT INTO COUNTRY (NAME) VALUES ('Palestine');
   INSERT INTO COUNTRY (NAME) VALUES ('Panama');
   INSERT INTO COUNTRY (NAME) VALUES ('Papua New Guinea');
   INSERT INTO COUNTRY (NAME) VALUES ('Paraguay');
   INSERT INTO COUNTRY (NAME) VALUES ('Peru');
   INSERT INTO COUNTRY (NAME) VALUES ('Phillipines');
   INSERT INTO COUNTRY (NAME) VALUES ('Pitcairn Island');
   INSERT INTO COUNTRY (NAME) VALUES ('Poland');
   INSERT INTO COUNTRY (NAME) VALUES ('Portugal');
   INSERT INTO COUNTRY (NAME) VALUES ('Puerto Rico');
   INSERT INTO COUNTRY (NAME) VALUES ('Qatar');
   INSERT INTO COUNTRY (NAME) VALUES ('Republic of Montenegro');
   INSERT INTO COUNTRY (NAME) VALUES ('Republic of Serbia');
   INSERT INTO COUNTRY (NAME) VALUES ('Reunion');
   INSERT INTO COUNTRY (NAME) VALUES ('Romania');
   INSERT INTO COUNTRY (NAME) VALUES ('Russia');
   INSERT INTO COUNTRY (NAME) VALUES ('Rwanda');
   INSERT INTO COUNTRY (NAME) VALUES ('St Barthelemy');
   INSERT INTO COUNTRY (NAME) VALUES ('St Eustatius');
   INSERT INTO COUNTRY (NAME) VALUES ('St Helena');
   INSERT INTO COUNTRY (NAME) VALUES ('St Kitts-Nevis');
   INSERT INTO COUNTRY (NAME) VALUES ('St Lucia');
   INSERT INTO COUNTRY (NAME) VALUES ('St Maarten');
   INSERT INTO COUNTRY (NAME) VALUES ('St Pierre & Miquelon');
   INSERT INTO COUNTRY (NAME) VALUES ('St Vincent & Grenadines');
   INSERT INTO COUNTRY (NAME) VALUES ('Saipan');
   INSERT INTO COUNTRY (NAME) VALUES ('Samoa');
   INSERT INTO COUNTRY (NAME) VALUES ('Samoa American');
   INSERT INTO COUNTRY (NAME) VALUES ('San Marino');
   INSERT INTO COUNTRY (NAME) VALUES ('Sao Tome & Principe');
   INSERT INTO COUNTRY (NAME) VALUES ('Saudi Arabia');
   INSERT INTO COUNTRY (NAME) VALUES ('Senegal');
   INSERT INTO COUNTRY (NAME) VALUES ('Seychelles');
   INSERT INTO COUNTRY (NAME) VALUES ('Sierra Leone');
   INSERT INTO COUNTRY (NAME) VALUES ('Singapore');
   INSERT INTO COUNTRY (NAME) VALUES ('Slovakia');
   INSERT INTO COUNTRY (NAME) VALUES ('Slovenia');
   INSERT INTO COUNTRY (NAME) VALUES ('Solomon Islands');
   INSERT INTO COUNTRY (NAME) VALUES ('Somalia');
   INSERT INTO COUNTRY (NAME) VALUES ('South Africa');
   INSERT INTO COUNTRY (NAME) VALUES ('Spain');
   INSERT INTO COUNTRY (NAME) VALUES ('Sri Lanka');
   INSERT INTO COUNTRY (NAME) VALUES ('Sudan');
   INSERT INTO COUNTRY (NAME) VALUES ('Suriname');
   INSERT INTO COUNTRY (NAME) VALUES ('Swaziland');
   INSERT INTO COUNTRY (NAME) VALUES ('Sweden');
   INSERT INTO COUNTRY (NAME) VALUES ('Switzerland');
   INSERT INTO COUNTRY (NAME) VALUES ('Syria');
   INSERT INTO COUNTRY (NAME) VALUES ('Tahiti');
   INSERT INTO COUNTRY (NAME) VALUES ('Taiwan');
   INSERT INTO COUNTRY (NAME) VALUES ('Tajikistan');
   INSERT INTO COUNTRY (NAME) VALUES ('Tanzania');
   INSERT INTO COUNTRY (NAME) VALUES ('Thailand');
   INSERT INTO COUNTRY (NAME) VALUES ('Togo');
   INSERT INTO COUNTRY (NAME) VALUES ('Tokelau');
   INSERT INTO COUNTRY (NAME) VALUES ('Tonga');
   INSERT INTO COUNTRY (NAME) VALUES ('Trinidad & Tobago');
   INSERT INTO COUNTRY (NAME) VALUES ('Tunisia');
   INSERT INTO COUNTRY (NAME) VALUES ('Turkey');
   INSERT INTO COUNTRY (NAME) VALUES ('Turkmenistan');
   INSERT INTO COUNTRY (NAME) VALUES ('Turks & Caicos Is');
   INSERT INTO COUNTRY (NAME) VALUES ('Tuvalu');
   INSERT INTO COUNTRY (NAME) VALUES ('Uganda');
   INSERT INTO COUNTRY (NAME) VALUES ('United Kingdom');
   INSERT INTO COUNTRY (NAME) VALUES ('Ukraine');
   INSERT INTO COUNTRY (NAME) VALUES ('United Arab Erimates');
   INSERT INTO COUNTRY (NAME) VALUES ('United States of America');
   INSERT INTO COUNTRY (NAME) VALUES ('Uraguay');
   INSERT INTO COUNTRY (NAME) VALUES ('Uzbekistan');
   INSERT INTO COUNTRY (NAME) VALUES ('Vanuatu');
   INSERT INTO COUNTRY (NAME) VALUES ('Vatican City State');
   INSERT INTO COUNTRY (NAME) VALUES ('Venezuela');
   INSERT INTO COUNTRY (NAME) VALUES ('Vietnam');
   INSERT INTO COUNTRY (NAME) VALUES ('Virgin Islands (Brit)');
   INSERT INTO COUNTRY (NAME) VALUES ('Virgin Islands (USA)');
   INSERT INTO COUNTRY (NAME) VALUES ('Wake Island');
   INSERT INTO COUNTRY (NAME) VALUES ('Wallis & Futana Is');
   INSERT INTO COUNTRY (NAME) VALUES ('Yemen');
   INSERT INTO COUNTRY (NAME) VALUES ('Zaire');
   INSERT INTO COUNTRY (NAME) VALUES ('Zambia');
   INSERT INTO COUNTRY (NAME) VALUES ('Zimbabwe');
select * from country;

INSERT INTO activity (BODY) VALUES ('Bungie Jump');
INSERT INTO activity (BODY) VALUES ('Cart Racing');
INSERT INTO activity (BODY) VALUES ('Zafari');
INSERT INTO activity (BODY) VALUES ('Paintball');
INSERT INTO activity (BODY) VALUES ('Bike travel');
INSERT INTO activity (BODY) VALUES ('Museum guide');
select * from activity;

INSERT INTO CATEGORY (NAME) VALUES ("Adventure");
INSERT INTO CATEGORY (NAME) VALUES ("Historical");
INSERT INTO CATEGORY (NAME) VALUES ("Travel");
select * from category;

INSERT INTO TOUR (NAME, DESCRIPTION, RATING, LEAVE_DATE, RETURN_DATE, PRICE, SEATS, CATEGORY_FK,COUNTRY_FK) 
VALUES('Nature discovery Tour','Travel trough de wilds of Mexico',5,sysdate(),sysdate(),300,40,1,141);
INSERT INTO TOUR (NAME, DESCRIPTION, RATING, LEAVE_DATE, RETURN_DATE, PRICE, SEATS, CATEGORY_FK,COUNTRY_FK) 
VALUES('Museum Tour','Learn about the Inca culture',5,STR_TO_DATE('02-04-2021','%d-%m-%Y'), 
STR_TO_DATE('23-05-2021','%d-%m-%Y'),400,70,2,141);
INSERT INTO TOUR (NAME, DESCRIPTION, RATING, LEAVE_DATE, RETURN_DATE, PRICE, SEATS, CATEGORY_FK,COUNTRY_FK) 
VALUES('Beach discovery','Visit several beaches in CR',5,STR_TO_DATE('20-06-2021','%d-%m-%Y'), 
STR_TO_DATE('05-07-2021','%d-%m-%Y'),460,20,3,53);
INSERT INTO TOUR (NAME, DESCRIPTION, RATING, LEAVE_DATE, RETURN_DATE, PRICE, SEATS, CATEGORY_FK,COUNTRY_FK) 
VALUES('Bike Tour','Bike ride trough the mountains',3,STR_TO_DATE('21-08-2021','%d-%m-%Y'), 
STR_TO_DATE('30-08-2021','%d-%m-%Y'),60,20,3,53);
select * from tour;

SELECT * FROM tourdb.TOUR T INNER JOIN tourdb.COUNTRY C WHERE C.ID = T.COUNTRY_FK AND T.LEAVE_DATE > STR_TO_DATE('2021-02-28','%Y-%m-%d')AND T.RETURN_DATE < STR_TO_DATE('2021-08-03','%Y-%m-%d') AND UPPER(C.NAME) LIKE '%Cos%';


INSERT INTO FEATURE (TOUR_FK, ACTIVITY_FK) VALUES (1,3);
INSERT INTO FEATURE (TOUR_FK, ACTIVITY_FK) VALUES (1,6);
INSERT INTO FEATURE (TOUR_FK, ACTIVITY_FK) VALUES (1,5);
SELECT * FROM TOUR_ACTIVITIES;

DELETE FROM USER WHERE ID > 1;
SELECT * FROM USER;



SELECT * FROM tourdb.FAVORITE WHERE USER_ID = 1111;

insert into REVIEW (BODY, TOUR_FK) VALUES ('Muy buen tour me gusto mucho',1);
insert into REVIEW (BODY, TOUR_FK) VALUES ('Muy buen tour me gusto mucho y me diverti',1);
SELECT * FROM REVIEW WHERE TOUR_FK = 1;

delete from favorite where TOUR_ID = 1 AND USER_ID=1111;