CREATE OR REPLACE VIEW TOUR_ACTIVITIES AS SELECT AC.ID AC_ID, AC.BODY AC_BODY, T.ID TOUR_ID 
FROM ACTIVITY AC 
INNER JOIN FEATURE F ON F.ACTIVITY_FK = AC.ID 
INNER JOIN TOUR T ON F.TOUR_FK = T.ID;

DROP PROCEDURE IF EXISTS PUT_USER;
DELIMITER //
CREATE PROCEDURE PUT_USER
(IN P_ID INT, IN P_NAME VARCHAR(45), IN P_EMAIL VARCHAR(45), IN P_BIRTH_DATE DATE, 
IN P_PASSWORD VARCHAR(45), IN P_COUNTRY_ID INT)
BEGIN
	INSERT INTO USER (ID,NAME, EMAIL, BIRTH_DATE, PASSWORD, COUNTRY_FK) 
				VALUES (P_ID, P_NAME, P_EMAIL, P_BIRTH_DATE, P_PASSWORD, P_COUNTRY_ID);
END 
//DELIMITER ;

DROP PROCEDURE IF EXISTS PUT_TOUR;
DELIMITER //
CREATE PROCEDURE PUT_TOUR
(IN P_NAME VARCHAR(45), IN P_DESC VARCHAR(100), IN P_RATING FLOAT, IN P_LEAVE_DATE DATE, P_RETURN_DATE DATE,
IN P_PRICE DOUBLE, IN P_SEATS INT, IN P_CAT INT, IN P_COUN INT)
BEGIN
	INSERT INTO TOUR (NAME, DESCRIPTION, RATING, LEAVE_DATE, RETURN_DATE, PRICE, SEATS, CATEGORY_FK,COUNTRY_FK) 
	VALUES(P_NAME, P_DESC, P_RATING, P_LEAVE_DATE, P_RETURN_DATE, P_PRICE, P_SEATS, P_CAT, P_COUN);
END 
//DELIMITER ;

DROP PROCEDURE IF EXISTS LINK_ACTIVITY;
DELIMITER //
CREATE PROCEDURE LINK_ACTIVITY
(IN P_ID_TOUR INT, IN P_ID_ACT INT)
BEGIN
	INSERT INTO FEATURE (TOUR_FK, ACTIVITY_FK) VALUES (P_ID_TOUR,P_ID_ACT);
END 
//DELIMITER ;

INSERT INTO COUNTRY (NAME) VALUES ('Costa Rica');
INSERT INTO COUNTRY (NAME) VALUES ('USA');
INSERT INTO COUNTRY (NAME) VALUES ('Panama');
INSERT INTO COUNTRY (NAME) VALUES ('Italy');
INSERT INTO COUNTRY (NAME) VALUES ('Australia');
INSERT INTO COUNTRY (NAME) VALUES ('New Zeland');
INSERT INTO COUNTRY (NAME) VALUES ('Brazil');
INSERT INTO COUNTRY (NAME) VALUES ('Mexico');
select * from country;

INSERT INTO activity (BODY) VALUES ('Bungie Jump');
INSERT INTO activity (BODY) VALUES ('Cart Racing');
INSERT INTO activity (BODY) VALUES ('Zafari');
INSERT INTO activity (BODY) VALUES ('Paintball');
INSERT INTO activity (BODY) VALUES ('Bike travel');
INSERT INTO activity (BODY) VALUES ('Museum guide');
select * from activity;

INSERT INTO CATEGORY (NAME) VALUES ("Adventure");
INSERT INTO CATEGORY (NAME) VALUES ("Historical");
INSERT INTO CATEGORY (NAME) VALUES ("Travel");
select * from category;

INSERT INTO TOUR (NAME, DESCRIPTION, RATING, LEAVE_DATE, RETURN_DATE, PRICE, SEATS, CATEGORY_FK,COUNTRY_FK) 
VALUES('Nature discovery Tour','Travel trough de wilds of Mexico',5,sysdate(),sysdate(),300,40,1,9);
select * from tour;

INSERT INTO FEATURE (TOUR_FK, ACTIVITY_FK) VALUES (1,3);
INSERT INTO FEATURE (TOUR_FK, ACTIVITY_FK) VALUES (1,6);
INSERT INTO FEATURE (TOUR_FK, ACTIVITY_FK) VALUES (1,5);
SELECT * FROM TOUR_ACTIVITIES;

SELECT * FROM USER;
DELETE FROM USER WHERE ID = 1312;

select STR_TO_DATE('5,3,121','%d,%m,%Y');